### ISSUE TITLE
Patch doesn't apply py3.5 linux

### ISSUE THREAD

**Issue by JPFrancoia** [cloudmatrix/esky#113]
Hi,

I have a little problem with the patches. When I try to apply a patch, I get this error:

```
Traceback (most recent call last):
  File "/home/djipey/informatique/python/ChemBrows/updater.py", line 59, in run
    self.app.auto_update()
  File "/usr/lib/python3.5/site-packages/esky/__init__.py", line 626, in auto_update
    self._do_auto_update(version, callback)
  File "/usr/lib/python3.5/site-packages/esky/__init__.py", line 674, in _do_auto_update
    self.fetch_version(version, callback)
  File "/usr/lib/python3.5/site-packages/esky/__init__.py", line 716, in fetch_version
    loc = self.version_finder.fetch_version(self, version, callback)
  File "/usr/lib/python3.5/site-packages/esky/finder.py", line 80, in fetch_version
    for status in self.fetch_version_iter(app,version):
  File "/usr/lib/python3.5/site-packages/esky/finder.py", line 230, in fetch_version_iter
    self._prepare_version(app,version,local_path)
  File "/usr/lib/python3.5/site-packages/esky/finder.py", line 332, in _prepare_version
    apply_patch(uppath,f)
  File "/usr/lib/python3.5/site-packages/esky/patch.py", line 294, in apply_patch
    Patcher(target,stream,**kwds).patch()
  File "/usr/lib/python3.5/site-packages/esky/patch.py", line 569, in patch
    getattr(self,"_do_" + _COMMANDS[cmd])()
IndexError: list index out of range
```

I started myprogram_1.0, and the patch myprogram_1.1_from1.0.patch is present at http://localhost:8000

Also, applying updates from the full zip completely works, either with a local and a remote server.

EDIT:

This is from Linux, using cx_Freeze

**Comment by timeyyy** [comment]
are you using py2app? the test suite doesn't pick up the error?

**Comment by JPFrancoia** [comment]
Nope, I'm using cx_Freeze, on Linux.

**Comment by timeyyy** [comment]
@JPFrancoia can you do the following
```
git fetch cloudmatrix/py3k
git checkout -t cloudmatrix/py3k
git checkout py3k
python3.5 -m pytest 
```
the py3k branch is passing all tests on linux python 3.4, it might help us narrow down the issue

**Comment by JPFrancoia** [comment]
Hi, the tests crash immediately with:

```
python3.5 -m pytest
==================================================================================== test session starts =====================================================================================
platform linux -- Python 3.5.0, pytest-2.8.3, py-1.4.31, pluggy-0.3.1
rootdir: /home/djipey/informatique/python/esky, inifile: 
collected 0 items / 1 errors 

=========================================================================================== ERRORS ===========================================================================================
__________________________________________________________________________ ERROR collecting esky/tests/test_esky.py __________________________________________________________________________
esky/tests/test_esky.py:35: in <module>
    from esky import bdist_esky
esky/bdist_esky/__init__.py:32: in <module>
    import freeze_future
E   ImportError: No module named 'freeze_future'
================================================================================== 1 error in 0.15 seconds ===================================================================================
```

**Comment by timeyyy** [comment]
i rebased the 3k branch onto the latest master. you will have to delete your local py3k branch and pull it down again. (git pull will fail)

**Comment by JPFrancoia** [comment]
I deleted my local repo, to be sure, and cloned it again. On py3k, the last commit I get is ba822b037ae2b771cd7ae4846f308c85a595810e.

I don't encounter the import problem anymore, but the tests still fail with the same error:

```
------------------------------------------------------------------------------------ Captured stderr call ------------------------------------------------------------------------------------
/usr/lib/python3.5/site-packages/cx_Freeze/freezer.py:590: UserWarning: Duplicate name: 'importlib/__init__.pyc'
  outFile.writestr(zinfo, data)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
================================================================================== 1 failed in 3.16 seconds ==================================================================================
```

**Comment by timeyyy** [comment]
could you paste the rest of the error log

**Comment by JPFrancoia** [comment]
Voilà !

[out.txt](https://github.com/cloudmatrix/esky/files/53226/out.txt)

**Comment by timeyyy** [comment]
so to be clear you have no problem running 

`python3.5 setup.py bdist_esky`

the test is failing to even build a distribution...

**Comment by JPFrancoia** [comment]
Hum, yes I do have a problem running

```
python3.5 setup.py bdist_esky
```

It fails with

```
error: [Errno 2] No such file or directory: '/usr/lib/python35.zip'
```

Even when install esky from this branch, and try to build a normal project.

**Comment by timeyyy** [comment]
but it builds from the master branch? i guess i gotta get python3.5 and have a play

**Comment by JPFrancoia** [comment]
I can build a normal project with the master branch, but I can't run the tests with the master branch.

If I checkout to master and try to run the tests:

```
python -m pytest -x
==================================================================================== test session starts =====================================================================================
platform linux -- Python 3.5.0, pytest-2.8.3, py-1.4.31, pluggy-0.3.1
rootdir: /home/djipey/informatique/python/esky, inifile: 
collected 0 items / 1 errors 

=========================================================================================== ERRORS ===========================================================================================
__________________________________________________________________________ ERROR collecting esky/tests/test_esky.py __________________________________________________________________________
/usr/lib/python3.5/site-packages/_pytest/python.py:606: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
/usr/lib/python3.5/site-packages/py/_path/local.py:650: in pyimport
    __import__(modname)
E     File "/home/djipey/informatique/python/esky/esky/__init__.py", line 254
E       except OSError, e:
E                     ^
E   SyntaxError: invalid syntax
================================================================================== 1 error in 0.11 seconds ===================================================================================
```

**Comment by timeyyy** [comment]
yeh the tests aren't available on on master for python3... If you want a quick fix i would suggest using python3.4,
 i'm focusing my efforts on getting esky onto the py3k branch so i wouldn't be getting my hands dirty with this for a while. Feel free to post and i'll say/do what i can

**Comment by timeyyy** [comment]
The Index Error is raised when applying patches from remote urls. I'd like to find out why before merging the patch though.

**Comment by rfk** [comment]
Thanks for reaching out.  Unfortunately this project is no longer actively maintained, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
