### ISSUE TITLE
Pbm with distutils and cx_Freeze on OSX

### ISSUE THREAD

**Issue by ogrisel** [cloudmatrix/esky#17]
I am using esky with cx_Freeze-4.2.3 on Mac OSX 10.6.6 and I have an issue with an application calling the `get_platform` function from `distutils.util`.

To reproduce this using the tutorial just add the following line to the examples script:

```
diff --git a/tutorial/stage1/example.py b/tutorial/stage1/example.py
index 9b4f112..0a7cffc 100644
--- a/tutorial/stage1/example.py
+++ b/tutorial/stage1/example.py
@@ -1,4 +1,5 @@
-
+from distutils.util import get_platform
+print (get_platform())

 print ("HELLO WORLD")

```

The by building and running the example as usual, one get the following stacktrace:

```
$ rm -rf dist && python setup.py bdist_esky && (cd dist && unzip *.zip && cd example-app-0.1.macosx-10_6-universal && ./example)
[...]
Traceback (most recent call last):
  File "/Library/Python/2.6/site-packages/cx_Freeze/initscripts/Console.py", line 27, in <module>
    exec code in m.__dict__
  File "/var/folders/VQ/VQbKi1w7F8KNUU4382MrrU+++TI/-Tmp-/tmpW879Pl/scripts/example.py", line 5, in <module>
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/distutils/util.py", line 97, in get_platform
    cfgvars = get_config_vars()
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/distutils/sysconfig.py", line 525, in get_config_vars
    func()
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/distutils/sysconfig.py", line 382, in _init_posix
    raise DistutilsPlatformError(my_msg)
distutils.errors.DistutilsPlatformError: invalid Python installation: unable to open /lib/python2.6/config/Makefile (No such file or directory)
```

Any idea why this is happening?

**Comment by rfk** [comment]
Thanks for reaching out.  Unfortunately this project is no longer actively maintained, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
