### ISSUE TITLE
Esky update causes transacted file operations error.

### ISSUE THREAD

**Issue by Aico** [cloudmatrix/esky#46]
Here is the error I get when I run auto_update:

```
Traceback (most recent call last):
  File "__main__.py", line 838, in <module>
  File "__main__.py", line 331, in bootstrap
  File "__main__.py", line 358, in chainload
  File "__main__.py", line 834, in _chainload
  File "peekmonitor_osaka.py", line 49, in <module>
  File "esky\__init__.pyc", line 471, in cleanup
  File "esky\__init__.pyc", line 516, in _cleanup_actions
  File "esky\__init__.pyc", line 465, in cleanup
  File "esky\__init__.pyc", line 882, in install_version
  File "esky\__init__.pyc", line 914, in _unpack_bootstrap_env
  File "esky\fstransact\win32txf.pyc", line 109, in move
  File "esky\fstransact\win32txf.pyc", line 118, in _move
  File "esky\fstransact\win32txf.pyc", line 24, in wrapper
WindowsError: [Error 6805] The remote server or share does not support transacted file operations.
```

On the server I see that the update is requested twice.

```
weapon101s.ds.com - - [23/May/2013 10:47:25] "GET / HTTP/1.1" 200 -
weapon101s.ds.com - - [23/May/2013 10:47:26] "GET / HTTP/1.1" 200 -
weapon101s.ds.com - - [23/May/2013 10:47:26] "GET /hifg-1.1.1.win32.zip HTTP/1.1" 200 -
weapon101s.ds.susq.com - - [23/May/2013 10:48:08] "GET /hifg-1.1.1.win32.zip HTTP/1.1" 200 -
weapon101s.ds.susq.com - - [23/May/2013 10:49:06] "GET / HTTP/1.1" 200 -
weapon101s.ds.susq.com - - [23/May/2013 10:49:06] "GET / HTTP/1.1" 200 -
```

this is probably a network issue since the problem does not occur on the local network but only  when update from a remote site. Any ideas on how to solve this?

-Kenneth

**Comment by rfk** [comment]
Thanks for reaching out.  Unfortunately this project is no longer actively maintained, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
